### ISSUE TITLE
train.py problem

### ISSUE THREAD

**Issue by mquevedob** [zhouzypaul/bovw-classifier#3]
hi

  File ".\bovw\train.py", line 35, in <module>
    main()
  File ".\bovw\train.py", line 20, in main
    predictions = classifier.predict(testing_images)
  File "C:\RouBot\bovw\bovw\classifier.py", line 62, in predict
    hist_features = self.histogram_from_sift(sift_features=sift_features)  # get histogram
  File "C:\RouBot\bovw\bovw\classifier.py", line 160, in histogram_from_sift
    sift_features_of_all_images = np.concatenate(sift_features, axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate

i am getting this error when trying train.py

do you know what can cause it ?

**Comment by mquevedob** [comment]
sorry my mistake
i forgot to populate the test folder
it works great

**Comment by 2324773711** [comment]
why my sift_features has None?

**Comment by 2324773711** [comment]
Traceback (most recent call last):
  File "d:/digital-image-processing/bovw-classifier-main/bovw/train.py", line 37, in <module>
    main()
  File "d:/digital-image-processing/bovw-classifier-main/bovw/train.py", line 19, in main
    classifier.fit(training_images, training_classes)
  File "d:\digital-image-processing\bovw-classifier-main\bovw\classifier.py", line 44, in fit
    self.train_kmeans(sift_features=sift_features)
  File "d:\digital-image-processing\bovw-classifier-main\bovw\classifier.py", line 122, in train_kmeans
    sift_features=np.concatenate(sift_features, axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 49 has 0 dimension(s)
